# which database are your want to use
# options:
#   - mysql
#   - mongodb
database_type:

# database name
# note:
#   it will generate `database`_development `database`_test `database`_production for different environments
database:

# if database need authentication, you need to provide username and password.
username:
password:
